### ISSUE TITLE
Aerotech connection fail

### ISSUE THREAD

**Issue by LuisOme** [robmarkcole/aerotech#3]
Hi @robmarkcole , I tried the aerotech code, but i have this error:

do you know what I might be doing wrong?

![2022-06-13 17_24_41-1 1  Motor and 2 more pages - Profile 1 - Microsoft_ Edge](https://user-images.githubusercontent.com/107422565/173392758-77b212c2-a379-4691-bff6-48045a2ba6c0.png)

**Comment by robmarkcole** [comment]
Is it an XYZ stage? Appears to have found the X then failed

**Comment by LuisOme** [comment]
Yes, it is XYZ; sometimes it fails at X and sometimes at Y, it has never reached Z. 
The IP address to use is the one that appears in ipconfig for the ethernet?

**Comment by robmarkcole** [comment]
It has been several years and I really cannot remember the device. I think the ip would be shown on the display; also disconnecting and reconnecting the device from the network can help identify it

**Comment by robmarkcole** [comment]
I vaguely remember it needs to be in the right mode to listen on IP, and that I had to reset the device to factory settings to enable this mode

**Comment by LuisOme** [comment]
Thank you very much for the quick answer, I still can't find the problem.
 Is the function of the sockets to send via ASCII the commands to be executed?
I have activated the communication through this channel but the same problem keeps appearing. 
Attached is an image of how the command is sent in case you want to remember it.
![Código Socket Enviado](https://user-images.githubusercontent.com/107422565/173571125-e6a207ac-72b6-423b-a8b3-392b96fcd154.png)

**Comment by robmarkcole** [comment]
edit the `connect` method to print the errors and check you get `Connected` (or check the logs, not visible in jupyter notebook)

**Comment by LuisOme** [comment]
Yes, the connection is only established when I enter that IP and ports, but the next step still fails.
When I try to print the `read` between the line 57-58 marked in the image, I get nothing; and with a np.shape I just get: **()**
![Envio Socket No funciona](https://user-images.githubusercontent.com/107422565/173578544-baa5469f-8392-48e2-aefd-8c4cd303f696.jpg)
)

**Comment by robmarkcole** [comment]
Suggest trying a `sleep` after each `write_read`, might be erroring as waiting for a read

**Comment by LuisOme** [comment]
Still the same problem, I will try to contact Aerotech, I think it has to be a problem in the communication.
Could it be that an `eneable `is needed in the code?

**Comment by LuisOme** [comment]
I have finally been able to connect,
(problems with the IP of the network I was using) but I had to add an `enable `function to be able to perform several steps in a row, otherwise # errors would appear. 
If you want, I'll show you the added enable, but basically I use the `write.read` with ENABLE for each axis.
Thank you very much for the program, and above all for your time.

**Comment by robmarkcole** [comment]
@LuisOme if you can document the updated code here that could help future debugging, many thanks!

**Comment by LuisOme** [comment]
I don't know if this is the right way, I'm new in Github, in case you want to do it in another way, please let me know without any problem.

```

"""
This module holds the class for interacting with an Aerotech XYZ.
Author R.Cole
"""

import socket
import logging

EOS_CHAR = '\n'   # End of string character
ACK_CHAR = '%'    #  indicate success.
NAK_CHAR = '!'    #  command error.
FAULT_CHAR = '#'  #  task error.
TIMEOUT_CHAR = '$'

class Ensemble:
    """Class providing control over a single Aerotech XYZ stage."""
    def __init__(self, ip, port):
        """
        Parameters
        ----------
        ip : str
            The ip of the Ensemble, e.g. 'localhost'
        port : int
            The port, default 8000
        """
        self._ip = ip
        self._port = port
        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        logging.info('Ensemble instantiated.')

    def connect(self):
        """Open the connection."""
        try:
            self._socket.connect((self._ip, self._port))
            logging.info('Connected')
        except ConnectionRefusedError:
            logging.error("Unble to connect.")


    def enable(self):
        "Enable the axis"
        self.write_read('ENABLE X')
        self.write_read('ENABLE Y')
        self.write_read('ENABLE Z')
        logging.info('Enabled axis')


    def write_read(self, command):
        """This method writes a command and returns the response,
        checking for an error code.
        Parameters
        ----------
        command : str
            The command to be sent, e.g. HOME X
        Returns
        ----------
        response : str
            The response to a command
        """
        if EOS_CHAR not in command:
            command = ''.join((command, EOS_CHAR))

        self._socket.send(command.encode())
        read = self._socket.recv(4096).decode().strip()
        code, response = read[0], read[1:]
        if code != ACK_CHAR:
            logging.error("Error from write_read().")
        return response

    def home(self):
        """This method homes the stage."""
        self.write_read('HOME X')
        self.write_read('HOME Y')
        self.write_read('HOME Z')
        logging.info('Homed')

    def move(self, x_pos, y_pos, z_pos):
        """Move to an X Y Z
        Parameters
        ----------
        x_pos : double
            The x position required
        """
        command = "MOVEABS X%f XF10.0 Y%f YF10.0 Z%f ZF10.0" % (
            x_pos, y_pos, z_pos)
        self.write_read(command)
        logging.info('Command written: %s', command)

    def get_positions(self):
        """Method to get the latest positions.
        Returns
        ----------
        positions : dict
            The X,Y,Z positions.
        """
        x_pos = float(self.write_read('PFBK X'))
        y_pos = float(self.write_read('PFBK Y'))
        z_pos = float(self.write_read('PFBK Z'))
        positions = {'X':x_pos, 'Y':y_pos, 'Z':z_pos}
        logging.info('positions: %s', str(positions))
        return positions

    def close(self):
        """Close the connection."""
        self._socket.close()
        logging.info("Connection closed")

```

**Comment by robmarkcole** [comment]
@LuisOme nice, if you feel like making a pull request with these changes that would be great (and nice git practice)

**Comment by LuisOme** [comment]
Yes, sometimes fail in the X line, and others in the Y
